apiVersion: v1
kind: PersistentVolume
metadata:
  name: cp-zookeeper-log-pv
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 6Gi
  hostPath:
    path: "/mnt/zookeeper/log"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cp-zookeeper-data-pv
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 9Gi
  hostPath:
    path: "/mnt/zookeeper/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cp-kafka-data-pv
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Gi
  hostPath:
    path: "/mnt/kafka"
