---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-kafka-data
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-zookeeper-data
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-zookeeper-log
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
